### ISSUE TITLE
 t5-japanese/t5_japanese_classification.ipynb にて信頼度出力がでなくなっている

### ISSUE THREAD

**Issue by taotaotao3** [sonoisa/t5-japanese#2]
transformersのバージョン変更からなのか、予測評価の際のgenerateメソッドの引数のreturn_dict_in_generateや、output_scoresが使用できなくなっている。

**Comment by sonoisa** [comment]
@taotaotao3 さん

依存ライブラリのバージョンを上げましたので、最新版でお試しいただけますか？
なお、私の手元ではそういった問題は発生しませんでした。

https://colab.research.google.com/github/sonoisa/t5-japanese/blob/main/t5_japanese_classification.ipynb
